-- Enable Row Level Security (RLS) is generally good practice, 
-- but for simplicity of migration, we'll start with basic tables.
-- You can enable RLS later in the Supabase Dashboard.

-- 1. Users Table (Note: Supabase has a built-in auth.users table, 
-- but this replicates your existing custom users collection)
CREATE TABLE IF NOT EXISTS public.app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL, -- Recommend migrating to Supabase Auth instead
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Contacts Table
CREATE TABLE IF NOT EXISTS public.contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enrollments Table
CREATE TABLE IF NOT EXISTS public.enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  email TEXT NOT NULL,
  course_slug TEXT NOT NULL,
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Blogs Table
CREATE TABLE IF NOT EXISTS public.blogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Replaces 'id' number from Mongo
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  date TEXT NOT NULL, -- Kept as text to match schema, but DATE type is better
  read_time TEXT NOT NULL,
  author TEXT NOT NULL,
  image TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Blog Infos Table (Content)
CREATE TABLE IF NOT EXISTS public.blog_infos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE REFERENCES public.blogs(slug) ON DELETE CASCADE,
  content TEXT NOT NULL, -- HTML Content
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Courses Table (List view info)
CREATE TABLE IF NOT EXISTS public.courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  level TEXT NOT NULL,
  image TEXT NOT NULL,
  price TEXT NOT NULL,
  rating NUMERIC, -- Kept flexible
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Course Infos Table (Detailed info)
CREATE TABLE IF NOT EXISTS public.course_infos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE REFERENCES public.courses(slug) ON DELETE CASCADE,
  hero JSONB,            -- Stores badge, titlePrefix, etc.
  problem_solution JSONB, -- Stores title, paragraphs
  learning_points JSONB,  -- Array of points
  projects JSONB,        -- Array of projects
  curriculum JSONB,      -- Summary and sections
  reviews JSONB,         -- Array of reviews
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 8. Counters (Optional, largely replaced by SERIAL/IDENTITY in Postgres)
CREATE TABLE IF NOT EXISTS public.counters (
  id TEXT PRIMARY KEY,
  seq BIGINT DEFAULT 0
);

-- 9. Insert Admin User
INSERT INTO public.app_users (name, email, password, is_admin)
VALUES ('Admin User', 'ashutoshsalunkhe2004@gmail.com', '$2b$10$j89z/.jp2MEdA78Qk7p5Ze0wwW8n.lbCasxQMnrjeM.HY0wGM8ygym', TRUE)
ON CONFLICT (email) DO NOTHING;
